config/routes.rb
Rails.application.routes.draw do
  # TODO: use only in archive sidebar. See how made other system
  get ':year/:month', to: 'articles#index', year: /\d{4}/, month: /\d{1,2}/, as: 'articles_by_month', format: false
  get ':year/:month/page/:page', to: 'articles#index', year: /\d{4}/, month: /\d{1,2}/, as: 'articles_by_month_page', format: false
  get ':year', to: 'articles#index', year: /\d{4}/, as: 'articles_by_year', format: false
  get ':year/page/:page', to: 'articles#index', year: /\d{4}/, as: 'articles_by_year_page', format: false

  get 'articles.:format', to: 'articles#index', constraints: {format: 'rss'}, as: 'rss'
  get 'articles.:format', to: 'articles#index', constraints: {format: 'atom'}, as: 'atom'

  scope controller: 'xml', path: 'xml' do
    get 'articlerss/:id/feed.xml', action: 'articlerss', format: false
    get 'commentrss/feed.xml', action: 'commentrss', format: false
    get 'trackbackrss/feed.xml', action: 'trackbackrss', format: false
  end

  get 'xml/:format', to: 'xml#feed', type: 'feed', constraints: {format: 'rss'}, as: 'xml'
  get 'sitemap.xml', to: 'xml#feed', format: 'googlesitemap', type: 'sitemap', as: 'sitemap_xml'

  scope controller: 'xml', path: 'xml', as: 'xml' do
    scope action: 'feed' do
      get ':format/feed.xml', type: 'feed'
      get ':format/:type/:id/feed.xml'
      get ':format/:type/feed.xml'
    end
  end

  get 'xml/rsd', to: 'xml#rsd', format: false
  get 'xml/feed', to: 'xml#feed'

  # CommentsController
  resources :comments, as: 'admin_comments' do
    collection do
      match :preview, via: [:get, :post, :put, :delete]
    end
  end

  resources :trackbacks

  # I thinks it's useless. More investigating
  post "trackbacks/:id/:day/:month/:year", to: 'trackbacks#create', format: false

  # ArticlesController
  get '/live_search/', to: 'articles#live_search', as: :live_search_articles, format: false
  get '/search/:q(.:format)/page/:page', to: 'articles#search', as: 'search', defaults: {page: 1}
  get '/search(/:q(.:format))', to: 'articles#search'
  get '/search/', to: 'articles#search', as: 'search_base', format: false
  get '/archives/', to: 'articles#archives', format: false
  get '/page/:page', to: 'articles#index', page: /\d+/, format: false
  get '/pages/*name', to: 'articles#view_page', format: false
  get 'previews(/:id)', to: 'articles#preview', format: false
  get 'previews_pages(/:id)', to: 'articles#preview_page', format: false
  get 'check_password', to: 'articles#check_password', format: false
  get 'articles/markup_help/:id', to: 'articles#markup_help', format: false
  get 'articles/tag', to: 'articles#tag', format: false

  # SetupController
  match '/setup', to: 'setup#index', via: [:get, :post], format: false

  # TagsController (imitate inflected_resource)
  resources :tags, except: [:show, :update, :destroy, :edit]
  resources :tags, path: 'tag', only: [:show, :edit, :update, :destroy]
  get '/tag/:id/page/:page', to: 'tags#show', format: false
  get '/tags/page/:page', to: 'tags#index', format: false

  resources :authors, path: 'author', only: :show

  # ThemeController
  scope controller: 'theme', filename: /.*/ do
    get 'stylesheets/theme/:filename', action: 'stylesheets', format: false
    get 'javascripts/theme/:filename', action: 'javascript', format: false
    get 'images/theme/:filename', action: 'images', format: false
  end

  # For the tests
  get 'theme/static_view_test', format: false

  # For the statuses
  get '/notes', to: 'notes#index', format: false
  get '/notes/page/:page', to: 'notes#index', format: false
  get '/note/:permalink', to: 'notes#show', format: false

  get '/humans', to: 'text#humans', format: 'txt'
  get '/robots', to: 'text#robots', format: 'txt'

  # TODO: Check which of these routes are not needed.
  resources :accounts, only: [:index], format: false do
    collection do
      get 'confirm'
      get 'login'
      post 'login'
      get 'signup'
      post 'signup'
      get 'recover_password'
      post 'recover_password'
      get 'logout'
      post 'logout'
    end
  end

  namespace :admin do
    get '/', to: 'dashboard#index', as: 'dashboard'

    get 'cache', to: 'cache#show'
    delete 'cache', to: 'cache#destroy'

    resources :content, only: [:index, :new, :edit, :create, :update, :destroy], format: false do
      collection do
        get 'auto_complete_for_article_keywords'
        post 'autosave'
      end
    end

    resources :notes, only: [:index, :show, :edit, :create, :update, :destroy], format: false

    resources :pages, only: [:index, :new, :edit, :create, :update, :destroy], format: false

    resources :post_types, only: [:index, :edit, :create, :update, :destroy], format: false

    resources :profiles, only: [:index, :update], format: false

    resources :redirects, only: [:index, :edit, :create, :update, :destroy], format: false

    resources :sidebar, only: [:index, :update, :destroy] do
      collection do
        put :sortable
      end
    end

    resources :tags, only: [:index, :edit, :create, :update, :destroy], format: false

    resources :users, only: [:index, :new, :edit, :create, :update, :destroy], format: false
  end

  # Admin/XController
  %w{feedback resources sidebar textfilters themes settings seo}.each do |i|
    match "/admin/#{i}", controller: "admin/#{i}", action: :index, format: false, via: [:get, :post, :put, :delete] # TODO: convert this magic catchers to resources item to close un-needed HTTP method
    match "/admin/#{i}(/:action(/:id))", controller: "admin/#{i}", action: nil, id: nil, format: false, via: [:get, :post, :put, :delete] # TODO: convert this magic catchers to resources item to close un-needed HTTP method
  end

  root 'articles#index'

  get '*from', to: 'articles#redirect', format: false
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  serialize :modules
  validates :label, uniqueness: true

  ADMIN = 'admin'
  PUBLISHER = 'publisher'
  CONTRIBUTOR = 'contributor'

  def modules
    read_attribute(:modules) || []
  end

  def modules=(perms)
    perms = perms.collect { |p| p.to_sym unless p.blank? }.compact if perms
    write_attribute(:modules, perms)
  end

  def project_modules
    modules.collect do |mod|
      AccessControl.project_module(label, mod)
    end.uniq.compact
  end
end

app/controllers/admin/profiles_controller.rb
require 'fog'

class Admin::ProfilesController < Admin::BaseController
  before_action :set_user, only: [:index, :update]

  def index
    @profiles = Profile.order('id')
  end

  def update
    @user.resource = upload_avatar if params[:user][:filename]

    if @user.update(user_params)
      redirect_to admin_profiles_url, notice: I18n.t('admin.profiles.index.success')
    else
      render :index
    end
  end

  private

  def upload_avatar
    file = params[:user][:filename]

    mime = if file.content_type
             file.content_type.chomp
           else
             'text/plain'
           end

    Resource.create(upload: file, mime: mime, created_at: Time.now)
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = current_user
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:login, :password, :password_confirmation, :email, :firstname, :lastname, :nickname, :display_name, :notify_via_email, :notify_on_new_articles, :notify_on_comments, :profile_id, :text_filter_id, :state, :twitter_account, :twitter_oauth_token, :twitter_oauth_token_secret, :description, :url, :msn, :yahoo, :jabber, :aim, :twitter)
  end
end

app/views/admin/profiles/_form.html.erb
<%= form_for([:admin, @user], url: admin_profile_path(current_user)) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset class='form-horizontal'>
    <legend><%= t('.account_settings')%></legend>
    <div class='form-group'>
      <label class='control-label col-sm-2' for="user_login"><%= t('.login')%></label>
      <div class='col-sm-5'>
        <%= f.text_field :login, class: 'form-control' %>
      </div>
    </div>
    <div class='form-group'>
      <label class='control-label col-sm-2' for="user_password"><%= t('.password')%></label>
      <div class='col-sm-5'>
        <%= f.password_field :password, class: 'form-control' %>
      </div>
    </div>
    <div class='form-group'>
      <label class='control-label col-sm-2' for="user_password_confirmation"><%= t('.password_confirmation')%></label>
      <div class='col-sm-5'>
        <%= f.password_field :password_confirmation, :class => 'form-control' %>
      </div>
    </div>
    <div class='form-group'>
      <label class='control-label col-sm-2' for="user_email"><%= t('.email')%></label>
      <div class='col-sm-5'>
        <%= f.text_field :email, class: 'form-control' %>
      </div>
    </div>
    <% if controller.controller_name == 'users' %>
    <div class='form-group'>
      <label class='control-label col-sm-2' for="user_profile"><%= t('.profile')%></label>
      <div class='col-sm-5'>
        <%= f.collection_select :profile_id, Profile.order('id').all, :id, :label, { include_blank: false }, class: 'form-control' %>
      </div>
    </div>
    <div class='form-group'>
      <label class='control-label col-sm-2' for="user_state"><%= t('.user_status')%></label>
      <div class='col-sm-5'>
        <select name="user[state]" class='form-control'>
          <% User::STATUS.each do |state| %>
            <option value="<%= state %>" <%= 'selected' if @user.state == state %>><%= t("user.status.#{state}") %></option>
        <% end %>
        </select>
      </div>
    </div>
    <% end %>
  </fieldset>

  <fieldset class='form-horizontal'>
    <legend><%= t('.profile_settings')%></legend>
    <div class='form-group'>
      <label class='control-label col-sm-2' for="user_firstname"><%= t('.firstname') %></label>
      <div class='col-sm-5'>
        <%= f.text_field :firstname, class: 'form-control' %>
      </div>
    </div>
    <div class='form-group'>
      <label class='control-label col-sm-2' for="user_lastname"><%= t('.lastname') %></label>
      <div class='col-sm-5'>
        <%= f.text_field :lastname, class: 'form-control' %>
      </div>
    </div>
    <div class='form-group'>
      <label class='control-label col-sm-2' for="user_nickname"><%= t('.nickname') %></label>
      <div class='col-sm-5'>
        <%= f.text_field :nickname, class: 'form-control' %>
      </div>
    </div>
    <% unless @user.login.nil? %>
      <div class='form-group'>
        <label class='control-label col-sm-2' for="user_name"><%= t('.display_name') %></label>
        <div class='col-sm-5'>
          <select name="user[name]" id="user_name" class='form-control'>
            <%= options_for_select(@user.display_names, @user.name) %>
          </select>
        </div>
      </div>
    <% end %>
    <div class='form-group'>
      <label class='control-label col-sm-2' for="text_filter"><%= t('.article_filter') %></label>
      <div class='col-sm-5'>
        <select name="user[text_filter_id]" id="text_filter" class='form-control'>
          <%= options_for_select text_filter_options_with_id, @user.text_filter.id %>
        </select>
      </div>
    </div>
  </fieldset>

  <% unless controller.controller_name == 'users'%>
    <fieldset class='form-horizontal'>
      <legend><%= t('.avatar') %></legend>
      <p><%= display_user_avatar(current_user, 'thumb') %> <%= t('.avatar_current') %></p>
      <div class='form-group'>
        <label class='control-label col-sm-2' for="avatar"><%= t('.upload') %></label>
        <div class='col-sm-5'>
          <%= f.file_field :filename, class: 'input-file' %>
          <p class='help-block'><%= t('.upload_file') %></p>
        </div>
      </div>
    </fieldset>
  <% end %>

  <fieldset class='form-horizontal'>
    <legend><%= t('.notification_settings') %></legend>
    <div class='form-group'>
      <label class='control-label col-sm-2'><%= t('.notifications') %></label>
      <div class='col-sm-5'>
        <label class='checkbox' for="user_notify_via_email">
          <%= f.check_box :notify_via_email %>
          <%= t('.notification_email') %>
        </label>
        <label class='checkbox' for="user_notify_on_new_articles">
          <%= f.check_box :notify_on_new_articles %>
          <%= t('.notification_article') %>
        </label>
        <label class='checkbox' for="user_notify_on_comments">
          <%= f.check_box :notify_on_comments %>
          <%= t('.notification_comment') %>
        </label>
      </div>
    </div>
  </fieldset>

  <% unless controller.controller_name == 'users' %>

  <fieldset class='form-horizontal'>
    <legend><%= t('.twitter') %></legend>
    <% unless twitter_available?(this_blog, current_user) %>
      <p class='alert alert-warning'>
    <%= t(".how_to_setup_twitter", twitter_settings_link: link_to(t(".fill_the_twitter_credentials"), controller: 'admin/settings', action: 'write'), twitter_registration_link: link_to(t(".registered_your_application"), "https://dev.twitter.com/apps/new")) %>
    </p>
  <% end %>
    <div class='form-group'>
      <label class='control-label col-sm-2' for="user_twitter_account"><%= t('.twitter_account')%></label>
      <div class='col-sm-5'>
        <%= f.text_field :twitter_account, {class: 'form-control', disabled: twitter_available?(this_blog, current_user)} %>
        <p class='help-block'>The Twitter account you want to post with</p>
      </div>
    </div>
    <div class='form-group'>
      <label class='control-label col-sm-2' for="user_twitter_oauth_token"><%= t('.twitter_oauth')%></label>
      <div class='col-sm-5'>
        <%= f.text_field :twitter_oauth_token, {class: 'form-control', disabled: twitter_available?(this_blog, current_user)} %>
      </div>
    </div>
    <div class='form-group'>
      <label class='control-label col-sm-2' for="user_twitter_oauth_token_secret"><%= t('.twitter_oauth_secret')%></label>
      <div class='col-sm-5'>
        <%= f.text_field :twitter_oauth_token_secret, {class: 'form-control', disabled: twitter_available?(this_blog, current_user)} %>
      </div>
    </div>
  </fieldset>

  <fieldset class='form-horizontal'>
    <legend><%= t('.contact_settings')%></legend>
    <div class='alert alert-info'><%= t('.contact_explain', link: link_to(t('.author_page'), author_path(id: current_user.login))) %></div>
    <div class='form-group'>
      <label class='control-label col-sm-2' for="user_description"><%= t('.about')%></label>
      <div class='col-sm-5'>
        <%= f.text_area :description, {class: 'form-control', rows: 5} %>
      </div>
    </div>
    <div class='form-group'>
      <label class='control-label col-sm-2' for="user_url"><%= t('.website')%></label>
      <div class='col-sm-5'>
        <%= f.text_field :url, class: 'form-control' %>
      </div>
    </div>
    <div class='form-group'>
      <label class='control-label col-sm-2' for="user_msn"><%= t('.msn')%></label>
      <div class='col-sm-5'>
        <%= f.text_field :msn, class: 'form-control' %>
      </div>
    </div>
    <div class='form-group'>
      <label class='control-label col-sm-2' for="user_yahoo"><%= t('.yahoo')%></label>
      <div class='col-sm-5'>
        <%= f.text_field :yahoo, class: 'form-control' %>
      </div>
    </div>
    <div class='form-group'>
      <label class='control-label col-sm-2' for="user_jabber"><%= t('.jabber')%></label>
      <div class='col-sm-5'>
        <%= f.text_field :jabber, class: 'form-control' %>
      </div>
    </div>
    <div class='form-group'>
      <label class='control-label col-sm-2' for="user_aim"><%= t('.aim')%></label>
      <div class='col-sm-5'>
        <%= f.text_field :aim, class: 'form-control' %>
      </div>
    </div>
    <div class='form-group'>
      <label class='control-label col-sm-2' for="user_twitter"><%= t('.twitter')%></label>
      <div class='col-sm-5'>
        <%= f.text_field :twitter, class: 'form-control' %>
      </div>
    </div>
  </fieldset>
  <% end %>

  <div class='form-actions'>
    <hr>
    <%= link_to(t(".cancel"), {action: 'index'}) %>
    <%= t(".or") %>
    <%= submit_tag("Save", class: 'btn btn-success') %>
  </div>
<% end %>

app/views/admin/profiles/index.html.erb
<% content_for :page_heading do %>
  <h2>
    <i class="glyphicon glyphicon-large glyphicon-user"></i>
    <%= t(".your_profile") %>
  </h2>
<% end %>

<%= render 'form' %>