config/routes.rb
Rails.application.routes.draw do
  # TODO: use only in archive sidebar. See how made other system
  get ':year/:month', to: 'articles#index', year: /\d{4}/, month: /\d{1,2}/, as: 'articles_by_month', format: false
  get ':year/:month/page/:page', to: 'articles#index', year: /\d{4}/, month: /\d{1,2}/, as: 'articles_by_month_page', format: false
  get ':year', to: 'articles#index', year: /\d{4}/, as: 'articles_by_year', format: false
  get ':year/page/:page', to: 'articles#index', year: /\d{4}/, as: 'articles_by_year_page', format: false

  get 'articles.:format', to: 'articles#index', constraints: {format: 'rss'}, as: 'rss'
  get 'articles.:format', to: 'articles#index', constraints: {format: 'atom'}, as: 'atom'

  scope controller: 'xml', path: 'xml' do
    get 'articlerss/:id/feed.xml', action: 'articlerss', format: false
    get 'commentrss/feed.xml', action: 'commentrss', format: false
    get 'trackbackrss/feed.xml', action: 'trackbackrss', format: false
  end

  get 'xml/:format', to: 'xml#feed', type: 'feed', constraints: {format: 'rss'}, as: 'xml'
  get 'sitemap.xml', to: 'xml#feed', format: 'googlesitemap', type: 'sitemap', as: 'sitemap_xml'

  scope controller: 'xml', path: 'xml', as: 'xml' do
    scope action: 'feed' do
      get ':format/feed.xml', type: 'feed'
      get ':format/:type/:id/feed.xml'
      get ':format/:type/feed.xml'
    end
  end

  get 'xml/rsd', to: 'xml#rsd', format: false
  get 'xml/feed', to: 'xml#feed'

  # CommentsController
  resources :comments, as: 'admin_comments' do
    collection do
      match :preview, via: [:get, :post, :put, :delete]
    end
  end

  resources :trackbacks

  # I thinks it's useless. More investigating
  post "trackbacks/:id/:day/:month/:year", to: 'trackbacks#create', format: false

  # ArticlesController
  get '/live_search/', to: 'articles#live_search', as: :live_search_articles, format: false
  get '/search/:q(.:format)/page/:page', to: 'articles#search', as: 'search', defaults: {page: 1}
  get '/search(/:q(.:format))', to: 'articles#search'
  get '/search/', to: 'articles#search', as: 'search_base', format: false
  get '/archives/', to: 'articles#archives', format: false
  get '/page/:page', to: 'articles#index', page: /\d+/, format: false
  get '/pages/*name', to: 'articles#view_page', format: false
  get 'previews(/:id)', to: 'articles#preview', format: false
  get 'previews_pages(/:id)', to: 'articles#preview_page', format: false
  get 'check_password', to: 'articles#check_password', format: false
  get 'articles/markup_help/:id', to: 'articles#markup_help', format: false
  get 'articles/tag', to: 'articles#tag', format: false

  # SetupController
  match '/setup', to: 'setup#index', via: [:get, :post], format: false

  # TagsController (imitate inflected_resource)
  resources :tags, except: [:show, :update, :destroy, :edit]
  resources :tags, path: 'tag', only: [:show, :edit, :update, :destroy]
  get '/tag/:id/page/:page', to: 'tags#show', format: false
  get '/tags/page/:page', to: 'tags#index', format: false

  resources :authors, path: 'author', only: :show

  # ThemeController
  scope controller: 'theme', filename: /.*/ do
    get 'stylesheets/theme/:filename', action: 'stylesheets', format: false
    get 'javascripts/theme/:filename', action: 'javascript', format: false
    get 'images/theme/:filename', action: 'images', format: false
  end

  # For the tests
  get 'theme/static_view_test', format: false

  # For the statuses
  get '/notes', to: 'notes#index', format: false
  get '/notes/page/:page', to: 'notes#index', format: false
  get '/note/:permalink', to: 'notes#show', format: false

  get '/humans', to: 'text#humans', format: 'txt'
  get '/robots', to: 'text#robots', format: 'txt'

  # TODO: Check which of these routes are not needed.
  resources :accounts, only: [:index], format: false do
    collection do
      get 'confirm'
      get 'login'
      post 'login'
      get 'signup'
      post 'signup'
      get 'recover_password'
      post 'recover_password'
      get 'logout'
      post 'logout'
    end
  end

  namespace :admin do
    get '/', to: 'dashboard#index', as: 'dashboard'

    get 'cache', to: 'cache#show'
    delete 'cache', to: 'cache#destroy'

    resources :content, only: [:index, :new, :edit, :create, :update, :destroy], format: false do
      collection do
        get 'auto_complete_for_article_keywords'
        post 'autosave'
      end
    end

    resources :notes, only: [:index, :show, :edit, :create, :update, :destroy], format: false

    resources :pages, only: [:index, :new, :edit, :create, :update, :destroy], format: false

    resources :post_types, only: [:index, :edit, :create, :update, :destroy], format: false

    resources :profiles, only: [:index, :update], format: false

    resources :redirects, only: [:index, :edit, :create, :update, :destroy], format: false

    resources :sidebar, only: [:index, :update, :destroy] do
      collection do
        put :sortable
      end
    end

    resources :tags, only: [:index, :edit, :create, :update, :destroy], format: false

    resources :users, only: [:index, :new, :edit, :create, :update, :destroy], format: false
  end

  # Admin/XController
  %w{feedback resources sidebar textfilters themes settings seo}.each do |i|
    match "/admin/#{i}", controller: "admin/#{i}", action: :index, format: false, via: [:get, :post, :put, :delete] # TODO: convert this magic catchers to resources item to close un-needed HTTP method
    match "/admin/#{i}(/:action(/:id))", controller: "admin/#{i}", action: nil, id: nil, format: false, via: [:get, :post, :put, :delete] # TODO: convert this magic catchers to resources item to close un-needed HTTP method
  end

  root 'articles#index'

  get '*from', to: 'articles#redirect', format: false
end

app/controllers/admin/sidebar_controller.rb
# coding: utf-8
class Admin::SidebarController < Admin::BaseController
  def index
    @available = available
    @ordered_sidebars = Sidebar.ordered_sidebars
  end

  # Just update a single active Sidebar instance at once
  def update
    sidebar_config = params[:configure]
    sidebar = Sidebar.where(id: params[:id]).first
    old_s_index = sidebar.staged_position || sidebar.active_position
    sidebar.update_attributes sidebar_config[sidebar.id.to_s].permit!
    respond_to do |format|
      format.js do
        # render partial _target for it
        return render partial: 'target_sidebar', locals: { sortable_index: old_s_index, sidebar: sidebar }
      end
      format.html do
        return redirect_to(admin_sidebar_index_path)
      end
    end
  end

  def destroy
    @sidebar = Sidebar.where(id: params[:id]).first
    @sidebar && @sidebar.destroy
    respond_to do |format|
      format.html { return redirect_to(admin_sidebar_index_path) }
      format.js
    end
  end

  def publish
    Sidebar.apply_staging_on_active!
    PageCache.sweep_all
    redirect_to admin_sidebar_index_path
  end

  # Callback for admin sidebar sortable plugin
  def sortable
    sorted = params[:sidebar].map(&:to_i)

    Sidebar.transaction do
      sorted.each_with_index do |sidebar_id, staged_index|
        # DEV NOTE : Ok, that's a HUGE hack. Sidebar.available are Class, not
        # Sidebar instances. In order to use jQuery.sortable we need that hack:
        # Sidebar.available is an Array, so it's ordered. I arbitrary shift by?
        # IT'S OVER NINE THOUSAND! considering we'll never reach 9K Sidebar
        # instances or Sidebar specializations
        sidebar = if sidebar_id >= 9000
                    Sidebar.available_sidebars[sidebar_id - 9000].new
                  else
                    Sidebar.valid.find(sidebar_id)
                  end
        sidebar.update_attributes(staged_position: staged_index)
      end
    end

    @ordered_sidebars = Sidebar.ordered_sidebars
    @available = Sidebar.available_sidebars
    respond_to do |format|
      format.json do
        render json: { html: render_to_string('admin/sidebar/_config.html.erb', layout: false) }
      end
      format.html do
        return redirect_to admin_sidebar_index_path
      end
    end
  end

  protected

  # TODO: Rename and move to a AdminSidebarHelpers module. Or use in instance variable.
  def available
    ::Sidebar.available_sidebars
  end

  helper_method :available
end

app/helpers/sidebars/plugin_helper.rb
module Sidebars::PluginHelper
end

app/views/admin/sidebar/_available.html.erb
<div data-sortable="sidebar_<%= 9000 + available_counter %>" class='alert alert-success draggable'>
  <h3 class='light'><%= available.display_name %></h3>
  <div class='widget-content'>
    <p><%= available.description %></p>
  </div>
</div>

app/views/admin/sidebar/_available.json.erb
<div data-sortable="sidebar_<%= 9000 + available_counter %>" class='alert alert-success draggable'>
  <h3 class='light'><%= available.display_name %></h3>
  <div class='widget-content'>
    <p><%= available.description %></p>
  </div>
</div>

app/views/admin/sidebar/_config.html.erb
<div id="sidebar-config" class='row'>
  <div id="available" class='col-md-6'>
    <div class='well'>
      <h3><%= t(".available_items")%></h3>
      <div id="available_box">
        <% if @available.blank? %>
        <p class='alert-message warning'><%= t(".you_have_no_plugins_installed")%>.</p>
        <% else %>
          <%= render :partial => 'available', :collection => @available %>
        <% end %>
      </div>
    </div>
  </div>

  <div id="cnt-active" class='col-md-6'>
    <div class='well'>
      <h3 id="hdr-active">
        <%= t(".active_sidebar_items")%>
        <%= image_tag "spinner-blue.gif", :id => 'update_spinner',
          :style => 'display:none;' -%>
      </h3>
      <div id="active">
        <%= render :partial => 'target' %>
      </div>
    </div>
  </div>
</div>

app/views/admin/sidebar/_target.html.erb
<ul class="sortable">
  <%- @ordered_sidebars.each_with_index do |sidebar, index| -%>
    <%- next unless sidebar.id -%>
    <%= render partial: 'target_sidebar', locals: { sidebar: sidebar, sortable_index: index } %>
  <%- end -%>
  <%- if @ordered_sidebars.empty? -%>
  <li></li>
  <%- end -%>
</ul>

app/views/admin/sidebar/_target.json.erb
<ul class="sortable">
  <%- @ordered_sidebars.each_with_index do |sidebar, index| -%>
    <%- next unless sidebar.id -%>
    <%= render partial: 'target_sidebar', locals: { sidebar: sidebar, sortable_index: index } %>
  <%- end -%>
  <%- if @ordered_sidebars.empty? -%>
  <li></li>
  <%- end -%>
</ul>

app/views/admin/sidebar/_target_sidebar.html.erb
<li id="sidebar_<%= sidebar.id %>" class="sidebar_item" data-sortable="sidebar_<%= sidebar.id %>" >
  <%= link_to 'X', admin_sidebar_path(sidebar), {class: 'deletion_link', remote: true, method: :delete, :'data-confirm'=>'Are you sure?'} %>
  <%= form_tag admin_sidebar_path(sidebar.id), {remote: true, method: :put} do |f| %>
    <div class="active alert <%= class_for_admin_state(sidebar, sortable_index)%>">
      <h3 class='light'><%= sidebar.display_name %></h3>
      <div class='widget-content'>
        <p><%= sidebar.description %></p>
      </div>
    <div>
    <%- sidebar.class.fields.each do |row| %>
      <%= row.line_html(sidebar) %>
    <%- end %>
    <%- if sidebar.class.fields.length > 0 -%>
    <p>
      <%= submit_tag(t('.update'), class: 'btn btn-sm btn-success') %>
    </p>
    <%- end -%>
    </div>
  <%- end -%>
</li>

app/views/admin/sidebar/_target_sidebar.json.erb
<li class="sidebar_item" data-sortable="sidebar_<%= sidebar.id %>" >
  <%= link_to 'X', admin_sidebar_path(sidebar), {class: 'deletion_link', remote: true, method: :delete, :'data-confirm'=>'Are you sure?'} %>
  <%= form_tag admin_sidebar_path(sidebar.id), {remote: true, method: :put} do |f| %>
    <div class="active alert <%= class_for_admin_state(sidebar, sortable_index)%>">
      <h3 class='light'><%= sidebar.display_name %></h3>
      <div class='widget-content'>
        <p><%= sidebar.description %></p>
      </div>
    <div>
      <%- sidebar.class.fields.each do |row| %>
      <%= row.line_html(sidebar) %>
      <%- end %>
      <%- if sidebar.class.fields.length > 0 -%>
      <p>
        <%= submit_tag t('.update') %>
      </p>
      <%- end -%>
    </div>
  <%- end -%>
</li>

app/views/admin/sidebar/index.html.erb
<%- content_for :page_heading do %>
<i class="icon-large icon-sidebar"></i>
<h2 class="page-title"><%= t(".sidebar") %></h2>
<%- end %>

<div class='alert alert-info'>
  <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
  <p><%= t(".explain_how_its_works") %></p>
  <p><%= t(".download_more_plugins") %></p>
</div>
<p class='help-block'></p>

<%= form_tag(url_for(:action=>'publish'), :method => :post, :class => 'spinner') do %>
  <div class='form-actions'>
    <%= link_to(t(".cancel"), {action: 'index'}) %>
    <%= t(".or") %>
    <%= submit_tag(t('.publish_changes'), class: 'btn btn-success') %>
  </div>
<%- end -%>

<div id="messages">&nbsp;</div>

<%= render partial: 'config' %>

<%= form_tag(url_for(:action=>'publish'), :method => :post, :class => 'spinner') do %>
  <div class='form-group'>
    <%= link_to(t(".cancel"), {action: 'index'}) %>
    <%= t(".or") %>
    <%= submit_tag(t('.publish_changes'), class: 'btn btn-success') %>
  </div>
<% end %>